### PR TITLE
Add Logistic Regression & SVM + Metrics Data

### PR DESCRIPTION
**Pull request by alecluna**
## Description  ##

This pull request contains:

- Add Logistic Regression and applied to DF with 10,000 entries and ~4000 features. Currently getting 
  around 93% but this might be incorrect due to over-fitting. 

- SVM model to see results, hovering around ~91% with same amount of entries and features
- `.gitginore`

### CODE REVIEW

**Comment by DatChoob** [comment]
Please remove the .DS_Store and .ipynb_checkpoints/ToxicityCommentClassifier-checkpoint.ipynb
folder. Also can you add them to the .gitignore

We don't want these to be checked into git.

**Review by DatChoob — DISMISSED** [review]
Please remove the .DS_Store and .ipynb_checkpoints/ToxicityCommentClassifier-checkpoint.ipynb
folder. Also can you add them to the .gitignore
Can you also please clear outputs

We don't want these to be checked into git. It makes it easier to see the diff

**Comment by alecluna** [comment]
@DatChoob done ✅

**Review by DatChoob — APPROVED** [review]
Looks good. Good job!

**Pull request merged**
